name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run compile.sh
        run: ./compile.sh

      - name: Find ZIP files
        id: find-zip-files
        run: |
          find build -name "*.zip" -exec echo "::set-output name=zip_files::{}" \;
      - name: Upload compiled ZIP files
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.find-zip-files.outputs.upload_url }}
          asset_path: ${{ steps.find-zip-files.outputs.zip_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
